# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('balls_caught', 'Global Balls Caught'), ('specials_caught', 'Global Specials Caught'), ('manual', 'Manual Progress')], default='manual', max_length=20)),
                ('target_amount', models.PositiveIntegerField(default=100, help_text='Goal amount for the challenge')),
                ('manual_progress', models.PositiveIntegerField(default=0, help_text='Current progress (only for Manual type)')),
            ],
        ),
    ]
