# Generated by Django 6.0.4 on 2026-04-16 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
        ('bd_models', '0014_alter_ball_options_alter_ballinstance_options_and_more'),  # was 0015
        ('community_challenge', '0004_fix_duplicate_filter_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('goal_type', models.CharField(choices=[('balls', 'Balls Caught'), ('currency', 'Currency Earned')], default='balls', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('reward_config', models.JSONField(default=dict, help_text='Mapping of Rank to rewards in JSON format.')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='challengeprogress',
            name='cc_challenge_amount_idx',
        ),
        migrations.RemoveConstraint(
            model_name='challengeprogress',
            name='cc_unique_challenge_player',
        ),
        migrations.RemoveConstraint(
            model_name='challengereward',
            name='cc_unique_reward_per_challenge',
        ),
        migrations.DeleteModel(
            name='ChallengeSettings',
        ),
        migrations.RemoveField(
            model_name='communitychallenge',
            name='ball_filter',
        ),
        migrations.RemoveField(
            model_name='communitychallenge',
            name='special_filter',
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='community_challenge.challenge'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.player'),
        ),
        migrations.RemoveField(
            model_name='challengeprogress',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengeprogress',
            name='player',
        ),
        migrations.RemoveField(
            model_name='challengereward',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengereward',
            name='player',
        ),
        migrations.AddConstraint(
            model_name='challengeparticipant',
            constraint=models.UniqueConstraint(fields=('challenge', 'player'), name='unique_challenge_player'),
        ),
        migrations.DeleteModel(
            name='ChallengeProgress',
        ),
        migrations.DeleteModel(
            name='CommunityChallenge',
        ),
        migrations.DeleteModel(
            name='ChallengeReward',
        ),
    ]
